// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtbzllslflswpielwrsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YnpsbHNsZmxzd3BpZWx3cnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MjU0MjgsImV4cCI6MjA2MzMwMTQyOH0.GLRbWIIMRi1tRa-KhZHIYIl3uATSI6bLzyo3on9aH50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);